### ISSUE TITLE
New Settings

### ISSUE THREAD

**Issue by casperlamboo** [Doodle3D/Doodle3D-Slicer#25]
I started thinking of a new settings format because the old settings format wasn't completely representive of how the slice process worked. For instance in the old settings the bottom thickness was grouped with the bottom flow rate.
```
bottom:
  flowRate: 1.2
  speed: 40.0
  thickness: 0.4
```
This doesn't make sense as the bottom flowrate / speed only affects the first couple of layers (to make sure the model sticks to the build plate). In the new settings I've renamed this to `firstLayer`. I've also split up `fill` into `innerShell` and `outerShell` as it makes sense to seperatly edit these flowrates / speeds

```
dimensions:
  x: 200
  y: 200
  z: 200
heatedBed: false
nozzleDiameter: 0.4
filamentThickness: 2.85
temperature: 210
bedTemperature: 70
layerHeight: 0.15
brimOffset: 4.0
thickness:
  top: 1.2
  bottom: 1.2
  shell: 0.8
retraction:
  enabled: true
  amount: 3.0
  speed: 50.0
  minDistance: 4.0
travel:
  speed: 200.0
support:
  enabled: false
  acceptanceMargin: 1.5
  distanceY: 0.4
  gridSize: 6.0
  margin: 2.0
  plateSize: 4.0
  flowRate: 0.8
  speed: 40.0
innerShell:
  flowRate: 1.0
  speed: 50.0
outerShell:
  flowRate: 1.0
  speed: 40.0
innerInfill:
  flowRate: 1.0
  speed: 50.0,
  gridSize: 5.0
outerInfill:
  flowRate: 1.0
  speed: 50.0
brim:
  flowRate: 1.0
  speed: 40.0
firstLayer:
  flowRate: 1.2
  speed: 40.0
```
